name: Publish release

on:
    push:
        branches:
            - master
        paths:
            - 'src/pdfpc.version'

jobs:
    extract-version:
        runs-on: ubuntu-latest

        outputs:
            PDFPC_VERSION: ${{ steps.version-extract.outputs.PDFPC_VERSION }}

        steps:
        - uses: actions/checkout@v3

        - id: version-extract
          name: Extract release name
          run: |
              PDFPC_VERSION=$( head -n 1 src/pdfpc.version )
              echo "PDFPC_VERSION=$PDFPC_VERSION" >> $GITHUB_OUTPUT

    create-release:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        needs: [extract-version, build-demo-assets]

        if: ${{ !endsWith(needs.extract-version.outputs.PDFPC_VERSION, 'pre') }}
        
        env:
          PDFPC_VERSION: ${{ needs.extract-version.outputs.PDFPC_VERSION }}

        steps:
        - uses: actions/checkout@v3

        - uses: actions/download-artifact@v3
          with:
              name: pdfpc-demo.pdf

        - uses: actions/download-artifact@v3
          with:
              name: pdfpc-video-example.zip

        - name: Release
          uses: softprops/action-gh-release@v1
          with:
              body: "Release of ${{ env.PDFPC_VERSION }}"
              files: |
                  pdfpc-demo.pdf
                  pdfpc-video-example.zip
              tag_name: ${{ env.PDFPC_VERSION }}

    build-demo-assets:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Setup TexLive
          uses: teatimeguest/setup-texlive-action@v2
          with:
            packages: >-
                scheme-basic
                adjustbox
                beamer
                calc
                etoolbox
                hyperref
                inputenc
                menukeys
                listings
                relsize
                xspace
                xstring

        - name: demo-slides
          run: |
            cd demo/ && make

        - name: video-examples
          run: |
            cd demo/pdfpc-video-example && make

        - name: Save demo slides
          uses: actions/upload-artifact@v3
          with:
            name: pdfpc-demo.pdf
            path: demo/pdfpc-demo.pdf

        - name: Save video examples
          uses: actions/upload-artifact@v3
          with:
            name: pdfpc-video-example.zip
            path: demo/pdfpc-video-example/video-example.zip
